### ISSUE TITLE
Duplicate Rename gizmo for certain mods

### ISSUE THREAD

**Issue by aph3rson** [emipa606/ShelfRenamer#1]
Other mods may already offer their own gizmo to rename storage. ShelfRenamer has logic to detect Rimfridge which does this behavior:
https://github.com/emipa606/ShelfRenamer/blob/d33197f61e4aba976f563133d67749d24c2310d6/Source/ShelfRenamer/Patch_Building_Storage_GetGizmos.cs#L19-L25

However, other mods do this as well, including Project RimFactory Revived ([example](https://github.com/zymex22/Project-RimFactory-Revived/blob/3736983ddc2a0447adaab6a8f7c3d52b913d8332/Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs#L359-L366)).

Rather than detecting the specific `thingClass` of the storage item, we should look at the existing gizmos already on the instance. Looking for other gizmos named `Rename` (or translated equivalent) should be sufficient.

**Comment by aph3rson** [comment]
The new name-based detection works for RimFridge. However, it doesn't work for PRF, as they don't use a Harmony patch - rather, they call `Building_Storage.GetGizmos()` directly ([here](https://github.com/zymex22/Project-RimFactory-Revived/blob/3612d53b20ac4c32dd875fcb9e7c2a8f4bb229ac/Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs#L78-L79)), and add onto it afterwards ([here](https://github.com/zymex22/Project-RimFactory-Revived/blob/3612d53b20ac4c32dd875fcb9e7c2a8f4bb229ac/Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs#L80-L87)).

**Comment by emipa606** [comment]
Should be fixed with #2
